rule all:
    input:
        "final.txt"

# Below here are the rules of the workflow, which would be normally in separate *.smk files then

rule hello:
    output:
        "results.txt"
    resources:
        time = config["resources"]["time"]["verylongrun"],
        partition = config["resources"]["partition"]["small"]
    shell:
        "echo 'Hello, Snakemake!' > {output}"

rule process:
    input:
        "results.txt"
    output:
        "processed.txt"
    shell:
        "cat {input} | awk '{{print $1}}' > {output}"

rule finalize:
    input:
        "processed.txt"
    output:
        "final.txt"
    resources:
        time =  config["resources"]["time"]["shortrun"]
    shell:
        "cat {input} | sort > {output}"
