#################################
##
## Runtime variables

results-folder: "results/"

#################################
##
## Server configuration

resources:
    time: 
        verylongrun: 30
        longrun: 5
        shortrun: 1
    mem_per_cpu:
        highmem: 8000
        lowmem: 1000
    cpu_per_task:
        single_thread: 1
        multi_thread: 24
    partition:
        testing: "test"
        small: "small"
        highmem: "highmem"
        longrun: "longrun"